// Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

= Entwicklerhandbuch
Christoph Heck, Stefanie Schynol, Robin Pape, Joyce Odiagbe
:doctype: book
:toc: left
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: coderay
:icons: font
// :kroki-server-url: https://kroki.io

// https://github.com/asciidoctor/asciidoctorj
// https://github.com/asciidoctor/asciidoctor-diagram
// http://de.plantuml.com/classes.html
// http://de.plantuml.com/component.html
// https://github.com/odrotbohm/asciidoctor-plantuml

IMPORTANT: Copyright (C) 2020 - present Christoph Heck, Stefanie Schynol, Robin Pape, Joyce Odiagbe, Hochschule Karlsruhe. +
           Free use of this software is granted under the terms of the
           GNU General Public License (GPL) v3. +
           For the full text of the license, see the http://www.gnu.org/licenses/gpl-3.0.html[license] file.

== Der Applikationsserver

=== Der Applikationsserver im Überblick

Die Aktivitäten der Rollen Admin und Gast werden hier angezeigt.

.Use Cases
[plantuml,use-cases,svg]
----
include::use-cases.puml[]
----

Die benötigte Komponenten werden hier abgebildet. 

.Komponentendiagramm
[plantuml,komponenten,svg]
----
include::komponenten.puml[]
----

=== Die REST-Schnittstelle

Hier wird ein Boundary-Control-Entity Pattern gebildet. In Boundary wird die API dargestellt und in Control werden die Geschäftsvorfälle realisiert, beziehungsweise der Ablauf gesteuert. In Entity werden Entity Objekte passend zur Anwendung abgebildet. 

.Handler für die REST-Schnittstelle
[plantuml,FilmHandler,svg]
----
include::FilmHandler.puml[]
----

=== Der Anwendungskern

In diesem Diagramm sehen wir, dass die Daten verarbeitet werden. Objekte können nach der ID gefiltert, erstellt, gelöscht oder aktualisiert werden. 

.Anwendungskern mit Mongoose
[plantuml,FilmService,svg]
----
include::FilmService.puml[]
----

=== Interface für Entities und das Mongoose-Model

Dieses Diagramm zeigt die Abhängigkeiten und die Werte der Enums.  

.Entity, Model und Schema
[plantuml,Film,svg]
----
include::Film.puml[]
----

== Programmierrichtlinien für TypeScript und JavaScript

Für die Programmierung mit *TypeScript* und *JavaScript* wird folgende
Styleguides empfehlenswert:

[horizontal]
_Microsoft_:: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines
_Angular_:: https://angular.io/docs/ts/latest/guide/style-guide.html
_React_:: https://github.com/airbnb/javascript/tree/master/react
